### ISSUE TITLE
running demo on new image 

### ISSUE THREAD

**Issue by nghorbani** [jaehyunnn/ViTPose_pytorch#1]
Thanks for a simplification of the ViTPose. 

A quick run on a novel image yielded wierd results:
![000000000](https://user-images.githubusercontent.com/7373673/208551591-14aeaaeb-51a0-4ebf-8959-4121179fc6b1.jpeg)

**Comment by jaehyunnn** [comment]
Thanks for the reporting. 
Firstly, I modified the code to convert heatmap into coordinates that fit the actual image size.

To add an explanation, ViTPose basically resizes the input image to 256 X 192 (height X width). This size has a longer height cuz ViTPose assume that the cropped image after human detection will come in as a top-down pose estimation approach.

However, the image you entered has a longer width, resulting in a large interpolation in terms of width, causing misplacement of the coordinates. Therefore, I highly recommend you to try to detect people first and then try it with a cropped person image.
