### ISSUE TITLE
Config File Issues while training

### ISSUE THREAD

**Issue by Bavesh-B** [jaehyunnn/ViTPose_pytorch#2]
Hey @jaehyunnn ,
I was trying to finetune ViTPose-L on my own custom dataset using you repository. While doing that, I encountered with the following error:- " lr_mult = cfg.optimizer['paramwise_cfg']['layer_decay_rate']. KeyError: 'paramwise_cfg' ". This error occured in the train_model function where we try to access the optimizer's config values. However, this file has directly been imported from the official ViTPose repository and I think they are using some other base config files like one for coco to set all these attributes. I would like to know how to resolve the issue or if I should just create a new yaml file for ViT-L version and use that yaml file directly? 

Thanking you in advance,
Bavesh Balaji

**Comment by jaehyunnn** [comment]
Thank you for the reporting.

The training code was incomplete.
I just updated the training code, And It would work.

Best regards,
Jay

**Comment by Bavesh-B** [comment]
Hey Jay,
Thanks for the update. I will try it out and reach out if I have any other issues.

Regards,
Bavesh Balaji

**Comment by Bavesh-B** [comment]
Hey Jay,
I can see that after the latest commit, you have changed a major chunk of the training script. I would just like to confirm if it is just for understandability or if the previous training script was wrong?

Regards,
Bavesh Balaji

**Comment by jaehyunnn** [comment]
@Bavesh-B 
The latest commit was just to add the validation routine (loss for validation set) and would not affect training procedure.
hope it help you to work.

Regards,
Jay
