### ISSUE TITLE
about 'train_custom' coco  dataset 

### ISSUE THREAD

**Issue by KenAdamsJoseph** [jaehyunnn/ViTPose_pytorch#4]
Hello, 
The annotations file, person_keypoints_train_custom.json, is not mentioned on the readme page.
The file may be modified from person_keypoints_train2017.json
 What changes have been made? Could you please upload the custom files?  

Thanks for your time.

**Comment by jaehyunnn** [comment]
Thank you for your interests,

"train_custom" is for user's custom dataset. Its format would be same as original coco dataset. 
You can change it to ''train2017" for original coco dataset.

 Regards,
Jay.
