### ISSUE TITLE
Converting official checkpoints to the format used in this repo

### ISSUE THREAD

**Issue by Stack-it-up** [jaehyunnn/ViTPose_pytorch#6]
Hello and thank you for this very useful implementation (I have managed to run it on Jetson devices, unlike the official implementation). 

I have tried to use the official weights and configs for other models, provided here: https://github.com/ViTAE-Transformer/ViTPose, but I get some messages about key mismatch, such as
```
RuntimeError: Error(s) in loading state_dict for ViTPose:
	Unexpected key(s) in state_dict: "backbone.cls_token". 
```

If you could provide info about the parameter names you used in your model, I think I might work to something similar to this conversion script: https://github.com/open-mmlab/mmsegmentation/issues/1473

Best

**Comment by jaehyunnn** [comment]
@Stack-it-up 
Which model have you tried?

**Comment by Stack-it-up** [comment]
I have tried using the pre-trained models found in the official implementation, such as https://github.com/ViTAE-Transformer/ViTPose#results-from-this-repo-on-ms-coco-val-set-single-task-training :

in particular, I tried using the Small model (ViTPose-S aka ViTPose_small_coco_256x192) and the Base model with simple decoder (VitPose_base_simple_coco-256x192)

**Comment by jaehyunnn** [comment]
@Stack-it-up 

Sorry, I haven't implement for ViTPose-S as well as all models with simple decoder.

**Comment by himanshuydv11** [comment]
This will solve the problem.
model.load_state_dict(ckpt['state_dict'], strict=False)

**Comment by himanshuydv11** [comment]
This will solve the problem.
model.load_state_dict(ckpt['state_dict'], strict=False)
